name: Build and Release APK
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "gradle"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-home-cache-cleanup: true
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}

      - name: Setup secrets and build
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          if [ -n "$KEYSTORE_BASE64" ]; then
            echo "$KEYSTORE_BASE64" | base64 -d > app/menhazbit.jks
          fi
          chmod +x ./gradlew
          ./gradlew assembleRelease

      - name: Prepare release
        id: release
        run: |
          VERSION=$(grep 'versionName = ' app/build.gradle.kts | sed 's/.*versionName = "\(.*\)"/\1/')
          APK_NAME="Awake-v${VERSION}.apk"
          mv app/build/outputs/apk/release/app-release.apk "$APK_NAME"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "apk_name=$APK_NAME" >> $GITHUB_OUTPUT

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.release.outputs.apk_name }}
          path: ${{ steps.release.outputs.apk_name }}

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ steps.release.outputs.version }}
          body: |
            ## Awake v${{ steps.release.outputs.version }}
            
            A simple Android app to keep your screen awake.
            
            ### Installation
            1. Download the APK below
            2. Enable "Install from unknown sources" if needed
            3. Install and grant system write permission when prompted
          draft: false
          prerelease: false
          files: ${{ steps.release.outputs.apk_name }}
          generate_release_notes: true

